language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일 전송
notifications:
  email:
    recipients:
      - ayaysir0@naver.com


before_deploy:
#    - zip -r deretopic *
#    - mkdir -p deploy
#    - mv deretopic.zip deploy/deretopic.zip
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/deretopic.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_DERE
    secret_access_key: $AWS_SECRET_KEY_DERE
    bucket: springboot-deretopic-build # s3 bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_DERE
    secret_access_key: $AWS_SECRET_KEY_DERE
    bucket: springboot-deretopic-build # s3 bucket
    key: deretopic.zip
    bundle_type: zip
    application: springboot-deretopic # 웹 콘솔에서 등록한 코드디플로이 애플리케이션
    deployment_group: springboot-deretopic-group
    region: ap-northeast-2
    wait-until-deployed: true